name: clan_churn
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.1.5 <4.0.0'
dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: 6.1.0
  auto_size_text: ^3.0.0
  responsive_framework: ^1.4.0
  collapsible_sidebar: ^2.0.7
  dropdown_button2: ^2.3.9
  http: ^1.1.0
  responsive_builder: ^0.7.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  flutter_secure_storage: ^9.1.1
  bloc: ^8.1.4
  meta: ^1.9.1
  go_router: ^13.2.0
  shared_preferences: ^2.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/































